/*
  Copyright (C) 2014 National Institute For Space Research (INPE) - Brazil.

  This file is part of SciETL.

  SciETL is free software: you can
  redistribute it and/or modify it under the terms of the
  GNU Lesser General Public License as published by
  the Free Software Foundation, either version 3 of the License,
  or (at your option) any later version.

  SciETL is distributed in the hope that
  it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with SciETL. See LICENSE. If not, write to
  e-sensing team at <esensning-team@dpi.inpe.br>.
*/

/*!
  \file scietl/Version.hpp

  \brief Proxy file for the real scietl_version.hpp file.

  \author Gilberto Ribeiro de Queiroz
 */

#ifndef __SCIETL_VERSION_HPP__
#define __SCIETL_VERSION_HPP__

// include real SciETL versioning file
// generated by CMake at build configuration
#include "scietl_version.hpp"

#endif  // __SCIETL_VERSION_HPP__
